name: immortalwrt_24.10

on:
  workflow_dispatch:
  schedule:
    - cron: 00 17 * * *
  watch:
    types: started

env:
  CLASH_KERNEL: amd64
  UPLOAD_FIRMWARE: true
  UPLOAD_BIN_DIR: false
  UPLOAD_ARTIFACT: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  merge:
    runs-on: Ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
         target: [Lean]

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Cache build files
      uses: actions/cache@v3
      with:
        path: |
          ./openwrt/dl
        key: ${{ runner.os }}-openwrt-dl-${{ matrix.target }}
        restore-keys: |
          ${{ runner.os }}-openwrt-dl-

